import CMSNavbar from "../components/CMSNavbar";
import { ThemeProvider } from "../utils/Provider";
import "./globals.css";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<ThemeProvider>
					<CMSNavbar />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
